# Generated by Django 5.2.1 on 2025-05-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lutadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutador',
            name='historia',
            field=models.TextField(default='Sem história cadastrada.'),
        ),
        migrations.AddField(
            model_name='lutador',
            name='idade',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='lutador',
            name='profissao',
            field=models.CharField(default='Desconhecida', max_length=255),
        ),
    ]
